spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prime
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    strategies:
      inline:
        migrationNames: V1__Create_initial_schema

job:
  schedule:
    cron: "*/20 * * * * ?"